# Generated by Django 3.0.1 on 2021-10-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.IntegerField()),
                ('jobtype', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.IntegerField()),
                ('wname', models.CharField(max_length=200)),
                ('wphnno', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('location', models.CharField(max_length=200)),
                ('specialisation', models.CharField(max_length=200)),
            ],
        ),
    ]
